import AppKit
import JavaScriptCore
import Quartz
import AVKit
import CoreImage
import CoreGraphics
import AppKit
// Protocol 

@objc protocol NSStandardKeyBindingRespondingExports: JSExport, NSObjectExports {
  @objc func cancelOperation(_: Any?)
  @objc func capitalizeWord(_: Any?)
  @objc func centerSelectionInVisibleArea(_: Any?)
  @objc func changeCaseOfLetter(_: Any?)
  @objc func complete(_: Any?)
  @objc func deleteBackward(_: Any?)
  @objc func deleteBackwardByDecomposingPreviousCharacter(_: Any?)
  @objc func deleteForward(_: Any?)
  @objc func deleteToBeginningOfLine(_: Any?)
  @objc func deleteToBeginningOfParagraph(_: Any?)
  @objc func deleteToEndOfLine(_: Any?)
  @objc func deleteToEndOfParagraph(_: Any?)
  @objc func deleteToMark(_: Any?)
  @objc func deleteWordBackward(_: Any?)
  @objc func deleteWordForward(_: Any?)
  @objc (doCommandBySelector:) func doCommand(by: Selector)
  @objc func indent(_: Any?)
  @objc func insertBacktab(_: Any?)
  @objc func insertContainerBreak(_: Any?)
  @objc @available(OSX 10.5, *) func insertDoubleQuoteIgnoringSubstitution(_: Any?)
  @objc func insertLineBreak(_: Any?)
  @objc func insertNewline(_: Any?)
  @objc func insertNewlineIgnoringFieldEditor(_: Any?)
  @objc func insertParagraphSeparator(_: Any?)
  @objc @available(OSX 10.5, *) func insertSingleQuoteIgnoringSubstitution(_: Any?)
  @objc func insertTab(_: Any?)
  @objc func insertTabIgnoringFieldEditor(_: Any?)
  @objc func insertText(_: Any)
  @objc func lowercaseWord(_: Any?)
  @objc @available(OSX 10.6, *) func makeBaseWritingDirectionLeftToRight(_: Any?)
  @objc @available(OSX 10.6, *) func makeBaseWritingDirectionNatural(_: Any?)
  @objc @available(OSX 10.6, *) func makeBaseWritingDirectionRightToLeft(_: Any?)
  @objc @available(OSX 10.6, *) func makeTextWritingDirectionLeftToRight(_: Any?)
  @objc @available(OSX 10.6, *) func makeTextWritingDirectionNatural(_: Any?)
  @objc @available(OSX 10.6, *) func makeTextWritingDirectionRightToLeft(_: Any?)
  @objc func moveBackward(_: Any?)
  @objc func moveBackwardAndModifySelection(_: Any?)
  @objc func moveDown(_: Any?)
  @objc func moveDownAndModifySelection(_: Any?)
  @objc func moveForward(_: Any?)
  @objc func moveForwardAndModifySelection(_: Any?)
  @objc func moveLeft(_: Any?)
  @objc func moveLeftAndModifySelection(_: Any?)
  @objc func moveParagraphBackwardAndModifySelection(_: Any?)
  @objc func moveParagraphForwardAndModifySelection(_: Any?)
  @objc func moveRight(_: Any?)
  @objc func moveRightAndModifySelection(_: Any?)
  @objc func moveToBeginningOfDocument(_: Any?)
  @objc func moveToBeginningOfDocumentAndModifySelection(_: Any?)
  @objc func moveToBeginningOfLine(_: Any?)
  @objc func moveToBeginningOfLineAndModifySelection(_: Any?)
  @objc func moveToBeginningOfParagraph(_: Any?)
  @objc func moveToBeginningOfParagraphAndModifySelection(_: Any?)
  @objc func moveToEndOfDocument(_: Any?)
  @objc func moveToEndOfDocumentAndModifySelection(_: Any?)
  @objc func moveToEndOfLine(_: Any?)
  @objc func moveToEndOfLineAndModifySelection(_: Any?)
  @objc func moveToEndOfParagraph(_: Any?)
  @objc func moveToEndOfParagraphAndModifySelection(_: Any?)
  @objc @available(OSX 10.6, *) func moveToLeftEndOfLine(_: Any?)
  @objc @available(OSX 10.6, *) func moveToLeftEndOfLineAndModifySelection(_: Any?)
  @objc @available(OSX 10.6, *) func moveToRightEndOfLine(_: Any?)
  @objc @available(OSX 10.6, *) func moveToRightEndOfLineAndModifySelection(_: Any?)
  @objc func moveUp(_: Any?)
  @objc func moveUpAndModifySelection(_: Any?)
  @objc func moveWordBackward(_: Any?)
  @objc func moveWordBackwardAndModifySelection(_: Any?)
  @objc func moveWordForward(_: Any?)
  @objc func moveWordForwardAndModifySelection(_: Any?)
  @objc func moveWordLeft(_: Any?)
  @objc func moveWordLeftAndModifySelection(_: Any?)
  @objc func moveWordRight(_: Any?)
  @objc func moveWordRightAndModifySelection(_: Any?)
  @objc func pageDown(_: Any?)
  @objc func pageDownAndModifySelection(_: Any?)
  @objc func pageUp(_: Any?)
  @objc func pageUpAndModifySelection(_: Any?)
  @objc @available(OSX 10.8, *) func quickLookPreviewItems(_: Any?)
  @objc func scrollLineDown(_: Any?)
  @objc func scrollLineUp(_: Any?)
  @objc func scrollPageDown(_: Any?)
  @objc func scrollPageUp(_: Any?)
  @objc func scrollToBeginningOfDocument(_: Any?)
  @objc func scrollToEndOfDocument(_: Any?)
  @objc func selectAll(_: Any?)
  @objc func selectLine(_: Any?)
  @objc func selectParagraph(_: Any?)
  @objc func selectToMark(_: Any?)
  @objc func selectWord(_: Any?)
  @objc func setMark(_: Any?)
  @objc func swapWithMark(_: Any?)
  @objc func transpose(_: Any?)
  @objc func transposeWords(_: Any?)
  @objc func uppercaseWord(_: Any?)
  @objc func yank(_: Any?)
}

