{
  "name": "VueKit",
  "options": {
    "deploymentTarget": {
      "macOS": "10.15"
    },
    "defaultConfig": "Release"
  },
  "configs": {
    "Debug": "debug",
    "Release": "release"
  },
  "targets": {
    "VueKit": {
      "type": "framework",
      "platform": "macOS",
      "sources": [
        "Sources"
      ]
    }
  }
}